POST http://localhost:3000/api/placas-de-video HTTP/1.1
Content-Type: application/json

{
    "id": "016",
    "fabricante": "Prototype",
    "marca": "Prototype",
    "modelo": "Prototype",
    "memoria": "0 GB",
    "precio": "000000"
}

###

    PUT http://localhost:3000/api/placas-de-video/004 HTTP/1.1
    Content-Type: application/json

{
    "id": "004",
    "fabricante": "NVIDIA",
    "marca": "Nvidia",
    "modelo": "RTX 3090",
    "memoria": "24 GB",
    "precio": "960800"
}

###

PATCH http://localhost:3000/api/placas-de-video/004 HTTP/1.1
Content-Type: application/json

{
    "precio": "000000"
}

###

DELETE http://localhost:3000/api/placas-de-video/016 HTTP/1.1
Content-Type: application/json